### ISSUE TITLE
How to get all chat list

### ISSUE THREAD

**Issue by NightRannie** [misonomikadev/messenger-api.js#8]
I am using this library on electron , facebook login success but the request of api is not pass

I want to get a list of all sessions of the logged-in user

I don't think it will work. Can you give me an example

thanks, I really need help

**Comment by misonomikadev** [comment]
You mean all the chat thread for a messenger account?

**Comment by NightRannie** [comment]
yeah，It doesn't work when I call getFriendsList

**Comment by misonomikadev** [comment]
You needn't do that, you can get thread directly by get it from client, example client.threads.cache (sync),
If you want to fetch (async) it then use client.threads.fetch()

**Comment by NightRannie** [comment]
okay, I know
I logged in with email and password in my project to get AppState like fbstate.json
Whether to use appstate to new Client

**Comment by NightRannie** [comment]
Because my project requirement requires email login, I must do so

**Comment by misonomikadev** [comment]
> Because my project requirement requires email login, I must do so

We still working on login with email and password so this library can't login without fbstate.json (account cookie)

**Comment by misonomikadev** [comment]
Maybe v2 will have that thing :>

**Comment by NightRannie** [comment]
Is the account cookie copied from the facebook website?   I have tried and succeeded before
So I want to try adding email login to this library and applying it to my project

Allow any user to log in to my application

**Comment by misonomikadev** [comment]
yes, file fbstate.json is the cookie copied from facebook web.

**Comment by NightRannie** [comment]
thanks,  understand
