### ISSUE TITLE
Logging out unexpectedly.

### ISSUE THREAD

**Issue by MiDo-kun** [misonomikadev/messenger-api.js#9]
Copied the cookies and stored it on fbstate.json but the problem is that after logging in, it will automatically logged out.
Do you know the issue behind this? I tried other packages as well but still getting the same results. Thanks.

![image](https://github.com/misonomikadev/messenger-api.js/assets/72369026/c7400000-a34b-4311-9620-ba53387d8cf7)

**Comment by misonomikadev** [comment]
Did you logged out the bot account in browser after logged the bot with this package?

**Comment by MiDo-kun** [comment]
Nope I did not, after logging in the package it will automatically logged out in the browser.

**Comment by misonomikadev** [comment]
Hmmmmm, i don't know what going on, sometime facebook blocked the suspicious request from bot so let me investigate that :<

**Comment by MiDo-kun** [comment]
Let me know if you've found any clues, but based on my observations recently it looks like the Facebook API changed MQTT as messaging protocol, since this is the only one that works so far before this issue happened, you can check it [here](https://github.com/Schmavery/facebook-chat-api/issues/763)

**Comment by misonomikadev** [comment]
Nah bro, this package using mqtt to listen events from facebook, maybe something has changed since facebook update their web recently :<

**Comment by misonomikadev** [comment]
Anyway thanks for the useful information :>
